Web/Controllers/ComunController.cs
using BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Controllers
{
    public class ComunController : Controller
    {
        // GET: Comun
        public ActionResult ObtenerUsuarioSesion()
        {
            return Json(Comun.SessionHelper.GetUser(),JsonRequestBehavior.AllowGet);
        }
        

        public JsonResult ListarPersonas()
        {
            return Json(PersonaBL.Listar()
                          .Select(x => new { value = x.DNI + " - " + x.NombreCompleto, data = x.PersonaId })
                          .ToList()
            , JsonRequestBehavior.AllowGet);
        }
    }
}

Web/Controllers/UsuarioController.cs
using BE;
using BL;
using BL.modelo;
using Comun;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Filters;

namespace Web.Controllers
{
    [Autenticado]
    public class UsuarioController : Controller
    {
        // GET: Usuario
        public ActionResult Index()
        {
            return View(UsuarioBL.Listar(includeProperties: "persona"));
        }



        /// <summary>
        /// 
        /// </summary>
        /// <param name="id">Id del usuario</param>
        /// <param name="PersonaId">id de la persona a crear el usuario</param>
        /// <returns></returns>
        public ActionResult Mantener(int id = 0, int pPersonaId = 0)
        {

            if (id == 0)
            {

                usuario u = new usuario();
                u.Activo = true;

                persona p = PersonaBL.Obtener(pPersonaId);
                var nombreusuario = p.Nombres.Substring(0, 1) + p.Paterno;
                var cuenta = UsuarioBL.Contar(x => x.PersonaId == pPersonaId);
                if (cuenta > 0)
                    u.Nombre = nombreusuario + (cuenta + 1);
                else
                    u.Nombre = nombreusuario;

                u.PersonaId = pPersonaId;
                u.IndCambio = true;

                u.Clave = "202cb962ac59075b964b07152d234b70";//123
                UsuarioBL.Crear(u);

                id = u.UsuarioId;


            }



            return View(new MantenerUsuario
            {
                Usuario = UsuarioBL.Obtener(x => x.UsuarioId == id, "persona"),
                Roles = RolBL.ListarRoles(id),
                Oficinas = OficinaBL.ListarOficinas(),
                Cargos = CargoBL.Listar()
            });
        }

        public JsonResult listaPersonas(string query)
        {
            var lista = cargar();


            return Json(new
            {
                query = "Unit",
                suggestions = lista.Where(x => x.value.ToLower().Contains(query.ToLower())).ToList()
            }, JsonRequestBehavior.AllowGet);
            //return Json(lista, JsonRequestBehavior.AllowGet);
        }

        public List<personita> cargar()
        {
            var lista1 = PersonaBL.Listar();
            var lista2 = new List<personita>();
            foreach (persona p in lista1)
            {
                lista2.Add(new personita { value = p.NombreCompleto, data = p.PersonaId });
            }
            return lista2;
        }

        public class personita
        {
            public string value { get; set; }
            public int data { get; set; }

        }


        public class MantenerUsuario
        {
            public usuario Usuario { get; set; }
            public List<Roles> Roles { get; set; }
            public List<Oficinas> Oficinas { get; set; }
            public List<cargo> Cargos { get; set; }
        }


        //[HttpPost]
        //public JsonResult GuardarOficinas(usuario u, int[] o = null)
        //{
        //    var rm = new ResponseModel();
        //    if (o != null)
        //    {
        //        foreach (var i in o)
        //            u.oficina.Add(new oficina { OficinaId = i });
        //    }

        //    try
        //    {
        //        UsuarioBL.GuardarUsuarioOficinas(u);
        //        rm.SetResponse(true);
        //        rm.function = "fn.notificar()";
        //    }
        //    catch (Exception ex)
        //    {
        //        rm.SetResponse(false);
        //        rm.function = "fn.mensaje('" + ex.Message + "')";
        //    }

        //    return Json(rm);
        //}

        [HttpPost]
        public JsonResult GuardarRoles(usuario u, int[] r = null)
        {
            var rm = new ResponseModel();
            if (r != null)
            {
                foreach (var i in r)
                    u.usuario_rol.Add(new usuario_rol { UsuarioId = u.UsuarioId, RolId = i });
            }

            try
            {
                UsuarioBL.GuardarUsuarioRoles(u);
                rm.SetResponse(true);
                rm.function = "fn.notificar()";
            }
            catch (Exception ex)
            {
                rm.SetResponse(false);
                rm.function = "fn.mensaje('" + ex.Message + "')";
            }

            return Json(rm);
        }

        [HttpPost]
        public JsonResult GuardarUsuario(usuario Usuario, string pActivo)
        {
            var rm = new ResponseModel();
            try
            {
                usuario u2 = UsuarioBL.Obtener(x => x.UsuarioId == Usuario.UsuarioId);
                bool mismoUsuario = u2.Nombre.Equals(Usuario.Nombre);
                bool yaExiste = UsuarioBL.Contar(x => x.Nombre == Usuario.Nombre) > 0;
                if (!mismoUsuario&&yaExiste )
                {
                    rm.SetResponse(false);
                    rm.function = "fn.mensaje('El nombre de usuario ya existe.')";
                    return Json(rm); 
                }

                if (!string.IsNullOrEmpty(pActivo)) Usuario.Activo = true;
                UsuarioBL.ActualizarParcial(Usuario, x => x.Nombre, x => x.Activo,x=>x.OficinaId, x => x.CargoId);
                rm.SetResponse(true);
                rm.function = "fn.notificar()";
            }
            catch (Exception ex)
            {
                rm.SetResponse(false);
                rm.function = "fn.mensaje('" + ex.Message + "')";
            }

            return Json(rm);
        }

        [HttpPost]
        public JsonResult ReiniciarClave(int id)
        {
            var rm = new ResponseModel();
            try
            {
                var enc = Comun.HashHelper.MD5("123");
                UsuarioBL.ActualizarParcial(new usuario { UsuarioId = id, Clave = enc, IndCambio = true }, x => x.Clave, x => x.IndCambio);
                rm.SetResponse(true);
            }
            catch (Exception ex)
            {
                rm.SetResponse(false, ex.Message);
            }

            return Json(rm);
        }

    }
}

Web/Views/Usuario/Index.cshtml
@model IEnumerable<BE.usuario>

<div class="row" style="margin-bottom:0;">
    <div class="col s12 m12 l8" >
        <div class="card-panel">
            <div class="row" style="margin-bottom:0;">
                <form id="frmbuscar" method="post" action='@Url.Action("Mantener","Usuario")'>
                    <div class="input-field col s12 m7 l8">
                        <input type="hidden" id="txtPersonaId" name="pPersonaId" value="0" />
                        <i class="mdi-action-search prefix"></i>
                        <input id="autocompletar" type="text" class="validate"
                               data-url='@Url.Action("ListarPersonas","Comun")'
                               data-seleccion="txtPersonaId"
                               data-boton="btnCrearUsuario">
                        <label for="autocompletar">Buscar Persona</label>
                    </div>
                    <div class="input-field col s12 m5 l4">
                        <button onclick="crearUsuario()" class="btn waves-effect waves-light left" type="submit" name="action" id="btnCrearUsuario" disabled>
                            Crear usuario
                            <i class="mdi-action-done right"></i>
                        </button>
                    </div>
                </form>
            </div>
            
        </div>        
    </div>    
</div>


<div id="mail-app" class="section" style="padding-top:0">
    <div class="row">
        <div class="col s12">
            <nav class="red">
                <div class="nav-wrapper">
                    <div class="left col s8 m6 l5">
                        <ul>
                            <li>
                                <a class="email-menu"><i class="mdi-navigation-menu"></i></a>
                            </li>
                            <li>
                                <a class="email-type">GESTIÓN DE USUARIOS</a>
                            </li>

                        </ul>
                    </div>
                    <div class="col s4 m6 l7">
                        <ul class="right">
                            <li>
                                <a href="#!"><i class="mdi-content-archive"></i></a>
                            </li>
                            <li>
                                <a href="#!"><i class="mdi-action-delete"></i></a>
                            </li>

                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    
            <div class="col s12">

                <div id="email-list" class="col s12 m12 l12 card-panel z-depth-1">
                    <ul class="collection">
                        @foreach (var item in Model)
                        {
                            <li class="collection-item avatar email-unread"
                                ondblclick="MostrarEditar(@item.UsuarioId);">
                                <!--mostrar con doble clik-->

                                <span class="circle @if (@item.Activo) { <text>light-blue</text>} else { <text>red</text>}">@item.Nombre.Substring(0, 1)</span>

                                <span class="email-title">@item.Nombre</span>
                                <p class="truncate grey-text ultra-small">@item.persona.DNI - @item.persona.NombreCompleto</p>

                                <a class="secondary-content email-time">
                                    <span class="blue-text ultra-small">cel: @item.persona.Celular</span>
                                </a>

                            </li>
                        }

                    </ul>
                   
                </div>

               


          
        </div>

    </div>



</div>



@section scripts {


    
    <script>
        

        @*$(document).ready(function () {

            $('#autocomplete').autocomplete({
                serviceUrl: '@Url.Action("listaPersonas", "Usuario")',
                minChars: 2,
                onSelect: function (suggestion) {
                    console.log('You selected: ' + suggestion.value + ', ' + suggestion.data);
                    $("#PersonaId").val(suggestion.data);
                    document.getElementById("btnCrearUsuario").disabled = true;
                  
                },
                showNoSuggestionNotice: true,
                noSuggestionNotice: 'Lo siento, no hay resultados',
            });
        });*@


        function MostrarEditar(id) {
            window.location = '@Url.Action("Mantener", "Usuario")' + '/' + id;
        }

        function crearUsuario() {
            //alert($("#PersonaId").val());
            var PersonaId = $("#PersonaId").val();


            window.location = '@Url.Action("Mantener", "Usuario")' + '?id=0&pPersonaId=' + PersonaId;
           
            
        }

    </script>


}

Web/Views/Usuario/Mantener.cshtml
@model Web.Controllers.UsuarioController.MantenerUsuario
<div class="container">
    <div class="section">
        <div id="profile-page-header" class="card">
            <div class="card-image waves-effect waves-block waves-light">
                <img class="activator" src="~/images/user-profile-bg.jpg" alt="user background">
            </div>
            <figure class="card-profile-image">
                <img src="~/images/avatar.jpg" alt="profile image" class="circle z-depth-2 responsive-img activator">
            </figure>
            <div class="card-content">
                <div class="row">
                    <div class="col s3 offset-s2">
                        <h4 class="card-title grey-text text-darken-4">Roger Waters</h4>
                        <p class="medium-small grey-text">Project Manager</p>
                    </div>
                    <div class="col s2 center-align">
                        <h4 class="card-title grey-text text-darken-4">10+</h4>
                        <p class="medium-small grey-text">Work Experience</p>
                    </div>
                    <div class="col s2 center-align">
                        <h4 class="card-title grey-text text-darken-4">6</h4>
                        <p class="medium-small grey-text">Completed Projects</p>
                    </div>
                    <div class="col s2 center-align">
                        <h4 class="card-title grey-text text-darken-4">$ 1,253,000</h4>
                        <p class="medium-small grey-text">Busness Profit</p>
                    </div>
                    <div class="col s1 right-align">
                        <a class="btn-floating activator waves-effect waves-light darken-2 right">
                            <i class="mdi-action-perm-identity"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="card-reveal">
                <p>
                    <span class="card-title grey-text text-darken-4">Roger Waters <i class="mdi-navigation-close right"></i></span>
                    <span><i class="mdi-action-perm-identity cyan-text text-darken-2"></i> Project Manager</span>
                </p>

                <p>I am a very simple card. I am good at containing small bits of information. I am convenient because I require little markup to use effectively.</p>

                <p><i class="mdi-action-perm-phone-msg cyan-text text-darken-2"></i> +1 (612) 222 8989</p>
                <p><i class="mdi-communication-email cyan-text text-darken-2"></i> mail@domain.com</p>
                <p><i class="mdi-social-cake cyan-text text-darken-2"></i> 18th June 1990</p>
                <p><i class="mdi-device-airplanemode-on cyan-text text-darken-2"></i> BAR - AUS</p>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col s12 m6 l6">
        <div id="profile-card" class="card">
            <form action='@Url.Action("GuardarUsuario","Usuario")' method="post">
                <ul id="task-card" class="collection with-header">
                    <li class="collection-header cyan ">
                        <button data-ajax="true" type="submit" data-position="left" data-tooltip="Guardar Usuario"
                                class="right btn btn-floating btn-flat waves-effect waves-light pink accent-2 white-text tooltipped">
                            <i class="mdi-content-save"></i>
                        </button>
                        <input type="hidden" name="Usuario.UsuarioId" value="@Model.Usuario.UsuarioId" />
                        <div class="bannerUsuario">
                            <h5 class="task-card-title ">
                                @Model.Usuario.persona.NombreCompleto
                            </h5>
                        </div>

                    </li>
                </ul>
                <div class="MyCard-content encerrar">
                    <img src="~/images/avatar.jpg" alt="" class="circle responsive-img activator card-profile-MyImage">

                    <ul id="profile-page-about-details">
                        <li class="collection-item">
                            <div class="row">
                                <div class="col s5 grey-text darken-1"><i class="mdi-notification-phone-in-talk"></i> Celular</div>
                                <div class="col s7 grey-text text-darken-4 right-align">@Model.Usuario.persona.Celular</div>
                            </div>
                        </li>
                        <li class="collection-item">
                            <div class="row">
                                <div class="col s5 grey-text darken-1"><i class="mdi-maps-location-history"></i> DNI</div>
                                <div class="col s7 grey-text text-darken-4 right-align">@Model.Usuario.persona.DNI</div>
                            </div>
                        </li>
                        <li class="collection-item">
                            <div class="row">
                                <div class="col s5 grey-text darken-1"><i class="mdi-communication-email"></i> Correo</div>
                                <div class="col s7 grey-text text-darken-4 right-align">@Model.Usuario.persona.Correo</div>
                            </div>
                        </li>
                        <li class="collection-item">
                            <div class="row">
                                <div class="col s5 grey-text darken-1"><i class="mdi-social-domain"></i> Dirección </div>
                                <div class="col s7 grey-text text-darken-4 right-align"></div>
                            </div>
                        </li>
                    </ul>
                    <div class="input-field col s6">
                        <i class="mdi-social-person-outline prefix"></i>
                        <input id="txtUsuario" name="Usuario.Nombre" type="text" class="validate valid" value="@Model.Usuario.Nombre">
                        <label class="active" for="txtUsuario">Usuario</label>
                    </div>
                    <div class="input-field col s6">
                        @Html.DropDownListFor(x => x.Usuario.OficinaId, Model.Oficinas.Select(x => new SelectListItem { Value = x.OficinaId.ToString(), Text = x.Denominacion }))
                        <label for="Usuario_OficinaId">Oficina</label>
                    </div>
                    <div class="input-field col s6 ">
                        <input type="checkbox" name="pActivo" class="filled-in" id="chkActivo" @if (Model.Usuario.Activo) { <text> checked</text>} />
                        <label for="chkActivo">Usuario activo</label>
                    </div>
                    <div class="input-field col s6">
                        @Html.DropDownListFor(x => x.Usuario.CargoId, Model.Cargos.Select(x => new SelectListItem { Value = x.CargoId.ToString(), Text = x.Denominacion }))
                        <label for="Usuario_CargoId">Cargo</label>
                    </div>

                    <div class="row">
                        <div class="col s12 m12 l12">
                            <a onclick="reiniciar(@Model.Usuario.UsuarioId)" data-position="left" data-tooltip="Reiniciar contraseña"
                               class="btn btn-floating waves-effect waves-light cyan right tooltipped"><i class="mdi-navigation-refresh"></i></a>
                        </div>
                    </div>

                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />                    
                    <br />
                    <br />
                </div>
            </form>
        </div>
    </div>

    <div class="col s12 m6 l6">
        <form method="post" action='@Url.Action("GuardarRoles","Usuario")'>
            <ul id="task-card" class="collection with-header">
                <li class="collection-header cyan">
                    <button type="submit" data-ajax="true" data-position="left" data-tooltip="Guardar Roles"
                            class="right btn btn-floating btn-flat waves-effect waves-light pink accent-2 white-text tooltipped">
                        <i class="mdi-content-save"></i>
                    </button>
                    <h5 class="task-card-title">ROLES</h5>
                    <input type="hidden" name="u.UsuarioId" value="@Model.Usuario.UsuarioId" />
                </li>
                @foreach (var item in Model.Roles)
            {
                    <li class="collection-item dismissable">
                        <input type="checkbox" id="r_@item.RolId" name="r" value="@item.RolId" @if (item.Estado) { <text> checked</text>}>
                        <label for="r_@item.RolId" style="text-decoration: none;">
                            @item.Denominacion
                        </label>
                    </li>
                }

            </ul>
        </form>
    </div>

    @*<div class="col s12 m6 l6">
            <form method="post" action='@Url.Action("GuardarOficinas","Usuario")'>
                <ul id="task-card" class="collection with-header">
                    <li class="collection-header cyan">
                        <button type="submit" data-ajax="true" data-position="left" data-tooltip="Guardar Oficinas"
                                class="right btn btn-floating btn-flat waves-effect waves-light pink accent-2 white-text tooltipped">
                            <i class="mdi-content-save"></i>
                        </button>

                        <h5 class="task-card-title">OFICINAS</h5>
                        <input type="hidden" name="u.UsuarioId" value="@Model.Usuario.UsuarioId" />
                    </li>
                    @foreach (var item in Model.Oficinas)
                {
                        <li class="collection-item dismissable">
                            <input type="checkbox" id="o_@item.OficinaId" name="o" value="@item.OficinaId" @if (item.Estado) { <text> checked</text>}>
                            <label for="o_@item.OficinaId" style="text-decoration: none;">
                                @item.Denominacion
                            </label>
                        </li>
                    }
                </ul>
            </form>
        </div>*@
</div>

@section scripts{
    <script>
        function reiniciar(u) {
            swal({
                title: "Estas seguro de Reiniciar la Clave?",
                text: "Esta acción reinicia la clave del usuario a 123",
                type: "warning",
                showCancelButton: true,
                cancelButtonText: "Cancelar",
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Reiniciar",
                closeOnConfirm: false
            }, function () {
                $.ajax({
                    data: { id: u },
                    url: '@Url.Action("ReiniciarClave", "Usuario")',
                    type: 'post',
                    success: function (d) {
                        if (d.response) swal("Reiniciado!", "La clave ha sido reiniciada.", "success");
                        else fn.mensaje(d.message);
                    },
                    error: function (jqXHR, textStatus, errorThrown) { alert(errorThrown); }
                });
            });
        }

    </script>

}