Web/Controllers/Acta/NacimientoController.cs
using System;
using System.Web;
using System.Web.Mvc;
using BL;
using BE;
using Models;
using System.IO;
using Web.Filters;

namespace Web.Controllers
{
    [Autenticado]
    public class NacimientoController : Controller
    {
        private const string RUTA_BASE = "~/Actas/Nacimiento/";
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult Buscar(string clave = "")
        {
            return PartialView(NacimientoBL.ListarNacimientos(clave.Trim()));
        }
        public ActionResult Mantener(int id = 0)
        {
            var nac = new nacimiento();
            if (id == 0)
            {
                var max = NacimientoBL.ObtenerUltimoLibro();
                nac.NroLibro = max[0];
                nac.NroActa = max[1] + 1;
                nac.Fecha = DateTime.Now;
                nac.Sexo = "M";
            }
            else
                nac = NacimientoBL.Obtener(id);

            return View(nac);
        }

        [HttpPost]
        public JsonResult Guardar(nacimiento nac)
        {
            var res = new Respuesta { respuesta = true };
            nac.ApellidoNombre = nac.ApellidoNombre.ToUpper();

            if (nac.NacimientoId == 0)
            {
                nac.Url = string.Empty;
                NacimientoBL.Crear(nac);
            }
            else
            {
                if (NacimientoBL.Contar(x => x.NroLibro == nac.NroLibro && x.NroActa == nac.NroActa && x.NacimientoId != nac.NacimientoId) > 0)
                {
                    res.respuesta = false;
                    res.error = "ERROR: Ya existe el acta " + nac.NroActa + " del libro " + nac.NroLibro + ". INGRESE OTRA NUMERACIÓN!";
                    return Json(res);
                }

                var ant = NacimientoBL.Obtener(x => x.NacimientoId == nac.NacimientoId, includeProperties: "nacimiento_anexo");
                if (ant.NroLibro != nac.NroLibro || ant.NroActa != nac.NroActa)
                {
                    if (ant.Url.Length > 0)
                    {
                        string rutaAnt = Path.Combine(Server.MapPath(RUTA_BASE), ant.Url);
                        string libro = "L" + nac.NroLibro.ToString();
                        string acta = nac.NroActa.ToString() + ".pdf";
                        string rutaLibro = Path.Combine(Server.MapPath(RUTA_BASE), libro);
                        nac.Url = libro + "/" + acta;

                        if (!Directory.Exists(rutaLibro))
                            Directory.CreateDirectory(rutaLibro);

                        string adjunto = Path.Combine(rutaLibro, acta);
                        if (System.IO.File.Exists(adjunto))
                            System.IO.File.Delete(adjunto);

                        if (System.IO.File.Exists(rutaAnt))
                            System.IO.File.Move(rutaAnt, adjunto);
                    }

                    foreach (var item in ant.nacimiento_anexo)
                    {
                        string acta_nueva = "L" + nac.NroLibro + "/" + nac.NroActa + "_" + item.Nacimiento_AnexoId + Path.GetExtension(item.url);
                        string ruta_acta_anterior = Server.MapPath(RUTA_BASE + item.url);

                        if (System.IO.File.Exists(ruta_acta_anterior))
                            System.IO.File.Move(ruta_acta_anterior, Server.MapPath(RUTA_BASE + acta_nueva));

                        item.url = acta_nueva;
                        NacimientoAnexoBL.Actualizar(item);
                        res.flag = true;
                    }

                }

                if (nac.Url == null) nac.Url = string.Empty;
                NacimientoBL.Actualizar(nac);
            }

            res.valor = nac.NacimientoId.ToString();
            return Json(res);
        }

        [HttpPost]
        public JsonResult Adjuntar(int NacimientoId, HttpPostedFileBase documento)
        {
            var rpt = new Respuesta
            {
                respuesta = true,
                error = ""
            };

            if (documento != null)
            {
                if (Path.GetExtension(documento.FileName).ToLower() != ".pdf")
                {
                    rpt.respuesta = false;
                    rpt.error = "Debe Ingresar solo Archivos PDF";
                    return Json(rpt);
                }

                var nac = NacimientoBL.Obtener(NacimientoId);
                var libro = "L" + nac.NroLibro.ToString();
                var acta = nac.NroActa + Path.GetExtension(documento.FileName);

                string rutaLibro = Path.Combine(Server.MapPath(RUTA_BASE), libro);
                if (!Directory.Exists(rutaLibro))
                    Directory.CreateDirectory(rutaLibro);

                string adjunto = Path.Combine(rutaLibro, acta);
                if (System.IO.File.Exists(adjunto))
                    System.IO.File.Delete(adjunto);

                documento.SaveAs(adjunto);

                nac.Url = libro + "/" + acta;
                NacimientoBL.Actualizar(nac);

                rpt.valor = RUTA_BASE.Substring(2, RUTA_BASE.Length - 2) + nac.Url;
            }
            else
            {
                rpt.respuesta = false;
                rpt.error = "Debe adjuntar un documento";
            }

            return Json(rpt);
        }

        public JsonResult Eliminar(int pNacimientoId)
        {
            var nac = NacimientoBL.Obtener(x => x.NacimientoId == pNacimientoId, includeProperties: "nacimiento_anexo");
            string ruta = Path.Combine(Server.MapPath(RUTA_BASE), "L" + nac.NroLibro.ToString(), nac.NroActa.ToString() + ".pdf");
            if (System.IO.File.Exists(ruta))
                System.IO.File.Delete(ruta);

            foreach (var item in nac.nacimiento_anexo)
            {
                if (System.IO.File.Exists(Server.MapPath(RUTA_BASE + item.url)))
                    System.IO.File.Delete(Server.MapPath(RUTA_BASE + item.url));
            }

            NacimientoBL.Eliminar(pNacimientoId);

            return Json(true, JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult MostrarAnexos(int pNacimientoId, bool editar)
        {
            ViewBag.editar = editar;
            return PartialView(NacimientoAnexoBL.Listar(x => x.NacimientoId == pNacimientoId));
        }
        [HttpPost]
        public JsonResult Anexo(int NacimientoId, HttpPostedFileBase documento)
        {
            var rpt = new Respuesta
            {
                respuesta = true,
                error = ""
            };

            if (documento != null)
            {
                if (Path.GetExtension(documento.FileName).ToLower() != ".pdf")
                {
                    rpt.respuesta = false;
                    rpt.error = "Debe Ingresar solo Archivos PDF";
                    return Json(rpt);
                }

                var nac = NacimientoBL.Obtener(NacimientoId);
                var anexo = NacimientoAnexoBL.Crear(new nacimiento_anexo { NacimientoId = NacimientoId, url = "" });
                string libro = "L" + nac.NroLibro;
                string acta = nac.NroActa + "_" + anexo.Nacimiento_AnexoId + Path.GetExtension(documento.FileName);


                string rutaLibro = Path.Combine(Server.MapPath(RUTA_BASE), libro);
                if (!Directory.Exists(rutaLibro))
                    Directory.CreateDirectory(rutaLibro);

                string adjunto = Path.Combine(rutaLibro, acta);
                if (System.IO.File.Exists(adjunto))
                    System.IO.File.Delete(adjunto);

                documento.SaveAs(adjunto);

                anexo.url = libro + "/" + acta;
                NacimientoAnexoBL.Actualizar(anexo);
            }
            else
            {
                rpt.respuesta = false;
                rpt.error = "Debe adjuntar un documento";
            }

            return Json(rpt);
        }

        public JsonResult EliminarAnexo(int id)
        {
            var anexo = NacimientoAnexoBL.Obtener(id);
            if (System.IO.File.Exists(Server.MapPath(RUTA_BASE + anexo.url)))
                System.IO.File.Delete(Server.MapPath(RUTA_BASE + anexo.url));

            var img = NacimientoAnexoBL.Eliminar(id);

            return Json(true);
        }


    }
}

Web/Controllers/ComunController.cs
using BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Controllers
{
    public class ComunController : Controller
    {
        // GET: Comun
        public ActionResult ObtenerUsuarioSesion()
        {
            return Json(Comun.SessionHelper.GetUser(),JsonRequestBehavior.AllowGet);
        }
        

        public JsonResult ListarPersonas()
        {
            return Json(PersonaBL.Listar()
                          .Select(x => new { value = x.DNI + " - " + x.NombreCompleto, data = x.PersonaId })
                          .ToList()
            , JsonRequestBehavior.AllowGet);
        }
    }
}

Web/Views/Nacimiento/Buscar.cshtml
@model List<BE.nacimiento>

<div id="email-list" class="col s12 m5 l5 card-panel z-depth-1">
    <ul class="collection">
        @{ int i = 0;}
        @foreach (var item in Model)
            {
                i++;
            <li class="collection-item avatar @if (i == 1) {<text>selected</text>}"
                ondblclick="MostrarEditar(@item.NacimientoId);"
                onclick="Mostrar(@item.NacimientoId,'@item.ApellidoNombre.Substring(0, 1)','@item.ApellidoNombre',@item.NroLibro,@item.NroActa,'@item.Url'); $(this).addClass('selected').siblings().removeClass('selected');">
                <span class="circle @if (@item.Url == string.Empty) { <text>red</text>} else { <text>light-blue</text>}">@item.ApellidoNombre.Substring(0, 1)</span>
                <span class="email-title">@item.ApellidoNombre</span>
                <p class="truncate grey-text ultra-small">Nacimiento: @item.Fecha.ToShortDateString()</p>
                <a class="secondary-content email-time"><span class="blue-text ultra-small">LIBRO @item.NroLibro ACTA @item.NroActa</span></a>
            </li>
        }
    </ul>
</div>
@if (Model.Count > 0)
{
    <div id="email-details" class="col s12 m7 l7 card-panel">
        <div class="email-content-wrap">
            <div class="row">
                <div class="col s10 m9 l9">
                    <input type="hidden" id="hdNacimientoId" value="@Model[0].NacimientoId" />
                    <ul class="collection">
                        <li class="collection-item avatar">
                            <span id="lblCorto" class="circle light-blue">
                                @Model[0].ApellidoNombre.Substring(0, 1)
                            </span>
                            <span id="lblNombre" class="email-title">
                                @Model[0].ApellidoNombre
                            </span>
                            <p class="truncate grey-text ultra-small">
                                Libro <span id="lblLibro">@Model[0].NroLibro</span>
                            </p>
                            <p class="grey-text ultra-small">
                                Acta <span id="lblActa">@Model[0].NroActa</span>
                            </p>
                        </li>
                    </ul>
                </div>
                <div class="col s1 m2 l2">
                    <a id="btnEditar" onclick="MantenerNacimiento();" class="btn-floating btn-large waves-effect waves-light cyan darken-2"><i class="mdi-editor-border-color"></i></a>
                    <p class="ultra-small">EDITAR</p>
                </div>
                <div class="col s1 m1 l1">
                    <a id="btnEliminar" onclick="EliminarNacimiento();" class="btn-floating btn-large waves-effect waves-light"><i class="mdi-content-clear"></i></a>
                    <p class="ultra-small">ELIMINAR</p>
                </div>
            </div>
            <div class="email-content">
                @if (string.IsNullOrEmpty(Model[0].Url))
                {
                    <iframe id="embedPdf2" src="@Href("~")Actas/no.jpg" style="width:100%;height:550px;" frameborder="0"></iframe>
                }
                else
                {
                    <iframe id="embedPdf2" src="@Href("~")Actas/Nacimiento/@Model[0].Url" style="width:100%;height:550px;" frameborder="0"></iframe>
                }
                <div id="listarAnexos">
                    @foreach (var item in Model[0].nacimiento_anexo)
                    {
                        <iframe src="~/Actas/Nacimiento/@item.url" style="width:100%;height:400px;" frameborder="0"></iframe>
                    }
                </div>
            </div>
        </div>
    </div>
}

Web/Views/Nacimiento/Index.cshtml
<!--start container-->
<div class="container">

    <div id="mail-app" class="section">
        <div class="row">
            <div class="col s12">
                <nav class="blue darken-2">
                    <div class="nav-wrapper">

                        <div class="left col s3 m3 l3">
                            <ul>
                                <li>
                                    <a href="#!" class="email-menu"><i class="mdi-navigation-menu"></i></a>
                                </li>
                                <li>
                                    <a href="#!" class="email-type">NACIMIENTOS</a>
                                </li>
                            </ul>

                        </div>
                        <div class="col s9 m9 l9 hide-on-med-and-down">
                            <form class="row">
                                <div class="input-field">
                                    <input id="btnb" type="text" placeholder="Buscar Ciudadano" autofocus>
                                    <label for="btnb">
                                        <i class="mdi-action-search"></i>
                                    </label>
                                </div>
                            </form>
                        </div>
                    </div>
                </nav>
            </div>
            <div class="col s12" id="listaActas">

            </div>

        </div>

        <!-- Compose acta -->
        <div class="fixed-action-btn" style="bottom: 50px; right: 19px;">
            <a class="btn btn-floating btn-large red" href='@Url.Action("Mantener","Nacimiento",new { id=0 })'>
                <i class="mdi-social-person-add"></i>
            </a>
        </div>  

    </div>
</div>
<!--end container-->

@section scripts{
    <script>
        $(function () {
            cargar();
            $("#btnb").keypress(function (event) {
                if (event.which == 13) {
                    event.preventDefault();
                    cargar();
                }
            });
        });

        function cargar() {
            var re = / /g;
            var url = "@Url.Action("Buscar","Nacimiento")" + "?clave=" + $('#btnb').val().replace(re, '%20');
            $.get('@Url.Action("ObtenerUsuarioSesion", "Comun")', function (d) {
                if (d == 0) location.reload();
                $("#listaActas").load(url);
            });

        };
        function CargarAnexos() {
            var url = "@Url.Action("MostrarAnexos", "Nacimiento")" + "?pNacimientoId=" + $("#hdNacimientoId").val() + "&editar=false";
            $("#listarAnexos").load(url);
        };
        function MantenerNacimiento() {
            window.location = '@Url.Action("Mantener", "Nacimiento")' + '/' + $("#hdNacimientoId").val();
        }
        function EliminarNacimiento() {
            swal({
                title: "Estas seguro de eliminar este registro?",
                text: "Esta acción elimina el registro y el acta digitalizada!",
                type: "warning",
                showCancelButton: true,
                cancelButtonText: "Cancelar",
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Eliminar",
                closeOnConfirm: false
            }, function () {
                $.ajax({
                    type: 'GET',
                    dataType: 'json',
                    url: '@Url.Action("Eliminar","Nacimiento")',
                    data: { pNacimientoId: $("#hdNacimientoId").val() },
                    success: function (res) {
                        swal({ title: "Eliminado!", text: "El registro ha sido eliminado.", type: "success", timer: 2000 }, function () {
                            window.location = '@Url.Action("Index", "Nacimiento")';
                        });
                    },
                    error: function (req, status, err) {
                        alert('Ocurrio un error: ' + err);
                    }
                });
            });


        }
        //$('.collection-item').click(function () {
        //    $(this).addClass("selected").siblings().removeClass("selected");
        //});
        function Mostrar(id, corto, n, l, a, url) {
            if ($("#hdNacimientoId").val() == id) return;

            $("#hdNacimientoId").val(id);
            $('#lblCorto').text(corto);
            $('#lblNombre').text(n);
            $('#lblLibro').text(l);
            $('#lblActa').text(a);

            if (url.length > 0)
                $('#embedPdf2').attr("src", "@Href("~")Actas/Nacimiento/" + url);
            else
                $('#embedPdf2').attr("src", "@Href("~")Actas/no.jpg");
            CargarAnexos();
        };

        function MostrarEditar(id) {
            window.location = '@Url.Action("Mantener", "Nacimiento")' + '/' + id;
        }
    </script>
}

Web/Views/Nacimiento/Mantener.cshtml
@model BE.nacimiento
<!--breadcrumbs start-->
<div id="breadcrumbs-wrapper">
    <!-- Search for small screen -->
    <div class="header-search-wrapper grey hide-on-large-only">
        <i class="mdi-action-search active"></i>
        <input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Explore Materialize">
    </div>
    <div class="container">
        <div class="row">
            <div class="col s12 m12 l12">
                <h5 class="breadcrumbs-title">GESTION DE NACIMIENTOS</h5>
                <ol class="breadcrumbs">
                    <li><a href='@Url.Action("Index","Home")'>Inicio</a></li>
                    <li><a href="@Url.Action("Index","Nacimiento")">Nacimientos</a></li>
                    <li class="active">Mantenimiento</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<!--breadcrumbs end-->

<div id="default-validation" class="section">
    <div class="row">
        <div class="col s12 m12 l6">
            <div class="card-panel">
                <h4 class="header2">Datos del Ciudadano</h4>
                <div class="row">
                    <form class="col s12" id="formValidate" method="post" action='@Url.Action("Guardar","Nacimiento")'>
                        <input type="hidden" name="NacimientoId" value="@Model.NacimientoId" />
                        <input type="hidden" name="Url" value="@Model.Url" />
                        <div class="row">
                            <div class="input-field col s12">
                                <i class="mdi-action-account-circle prefix"></i>
                                <label for="ApellidoNombre">Apellidos y Nombres*</label>
                                <input id="ApellidoNombre" name="ApellidoNombre" type="text" data-error=".errorTxt1" required minlength="5" value="@Model.ApellidoNombre">
                                <div class="errorTxt1"></div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s6">
                                <i class="mdi-action-assignment-ind prefix"></i>
                                <label for="NroLibro">Nro. Libro*</label>
                                <input id="NroLibro" name="NroLibro" type="number" data-error=".errorTxt2" class="required number" value="@Model.NroLibro">
                                <div class="errorTxt2"></div>
                            </div>
                            <div class="input-field col s6">
                                <i class="mdi-action-assignment prefix"></i>
                                <label for="NroActa">Nro. Acta*</label>
                                <input id="NroActa" name="NroActa" type="number" data-error=".errorTxt3" class="required number" value="@Model.NroActa">
                                <div class="errorTxt3"></div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="input-field col s6">
                                <i class="mdi-editor-insert-invitation prefix"></i>
                                <label for="Fecha">Fecha Nacimiento*</label>
                                <input id="Fecha" name="Fecha" type="text" data-error=".errorTxt4" class="datepicker required"
                                       value="@Model.Fecha.ToShortDateString()">
                                <div class="errorTxt4"></div>
                            </div>
                            <div class="col s6">
                                <label for="genter_select">Sexo</label>
                                <p>
                                    <input name="Sexo" type="radio" id="rbsexom" value="M" @if (Model.Sexo == "M") {  <text> checked</text> } />
                                    <label for="rbsexom">Masculino </label>
                                    -
                                    <input name="Sexo" type="radio" id="rbsexof" value="F" @if (Model.Sexo == "F") {  <text> checked</text> } />
                                    <label for="rbsexof">Femenino </label>
                                </p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s6">
                                <a class="btn waves-effect waves-light blue" href='@Url.Action("Index","Nacimiento")'>
                                    Regresar
                                    <i class="mdi-av-fast-rewind right"></i>
                                </a>
                            </div>

                            <div class="input-field col s6">
                                <button class="btn waves-effect waves-light right" type="submit" name="action">
                                    Guardar
                                    <i class="mdi-action-done right"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        @if (Model.NacimientoId > 0)
        {
            <div class="col s12 m12 l6">
                <div class="card-panel">
                    <h4 class="header2">Acta Principal de Nacimiento</h4>
                    <div class="row">
                        <form id="frmAdjuntar" method="post" action='@Url.Action("Adjuntar","Nacimiento")'>
                            <div class=" col s9">
                                <input type="hidden" name="NacimientoId" value="@Model.NacimientoId" />
                                <div class="file-field input-field">
                                    <div class="btn blue">
                                        <span>Buscar acta *.pdf</span>
                                        <input name="documento" type="file" accept="application/pdf">
                                    </div>
                                    <div class="file-path-wrapper">
                                        <input class="file-path validate" type="text">
                                    </div>
                                </div>
                            </div>
                            <div class="input-field col s3">
                                <button class="btn waves-effect waves-light right" type="submit">
                                    Subir
                                    <i class="mdi-file-file-upload right"></i>
                                </button>
                            </div>
                        </form>
                    </div>

                    @if (Model.Url.Length > 0)
                    {
                        <div class="row">
                            <iframe id="ifrNac" src="~/Actas/Nacimiento/@Model.Url" style="width:100%;height:400px;" frameborder="0"></iframe>
                        </div>
                    }
                    else
                    {
                        <div class="row">
                            <iframe id="ifrNac" style="width:100%;height:400px;" frameborder="0"></iframe>
                        </div>
                    }

                    <hr />
                    <h4 class="header2">Anotaciones</h4>
                    <div class="row">
                        <form id="frmAdjuntarAnexo" method="post" action='@Url.Action("Anexo","Nacimiento")'>
                            <input type="hidden" name="NacimientoId" value="@Model.NacimientoId" />
                            <div class=" col s9">
                                <div class="file-field input-field">
                                    <div class="btn blue">
                                        <span>Buscar Anotación *.pdf</span>
                                        <input name="documento" type="file" accept="application/pdf">
                                    </div>
                                    <div class="file-path-wrapper">
                                        <input class="file-path validate" type="text">
                                    </div>
                                </div>
                            </div>
                            <div class="input-field col s3">
                                <button class="btn waves-effect waves-light right" type="submit">
                                    Subir
                                    <i class="mdi-file-file-upload right"></i>
                                </button>
                            </div>
                        </form>
                    </div>
                    <div id="listarAnexos"></div>
                </div>
            </div>


        }
    </div>

    <div class="fixed-action-btn" style="bottom: 50px; right: 19px;">
        <a class="btn-floating btn-large red" href='@Url.Action("Mantener","Nacimiento",new { id=0 })'>
            <i class="mdi-social-person-add"></i>
        </a>
    </div>

</div>
@section scripts{
    <script type="text/javascript">
        $(function () {
            @if (Model.NacimientoId > 0)
            {
                <text>CargarAnexos();</text>
            }

            $(".datepicker").pickadate({ selectMonths: !0, selectYears: 50, format: 'dd/mm/yyyy' })

            $("#formValidate").validate({
                errorElement: 'div',
                errorPlacement: function (error, element) {
                    var placement = $(element).data('error');
                    if (placement) {
                        $(placement).append(error)
                    } else {
                        error.insertAfter(element);
                    }
                }
            });
            $("#formValidate").submit(function () {
                var form = $(this);

                form.ajaxSubmit({
                    dataType: 'JSON',
                    type: 'POST',
                    url: form.attr('action'),
                    success: function (r) {
                        
                        if (r.respuesta) {
                            @if (@Model.NacimientoId == 0) {
                                <text>  window.location = '@Url.Action("Mantener", "Nacimiento", new { id = "" })' + '/' + r.valor; return;</text>
                            }

                            Materialize.toast('Se Guardó Correctamente!', 4000);
                            if (r.flag)
                                CargarAnexos();

                        }
                        else
                            Materialize.toast(r.error, 4000);
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        alert(errorThrown);
                    }
                });
                return false;
            });
            $("#frmAdjuntar").submit(function () {
                var form = $(this);
                form.ajaxSubmit({
                    dataType: 'JSON',
                    type: 'POST',
                    url: form.attr('action'),
                    success: function (r) {
                        if (r.respuesta) {
                            Materialize.toast('Se Subió Correctamente!', 4000);
                            $('#ifrNac').attr("src", '@Href("~/")' + r.valor);
                        }
                        else { Materialize.toast(r.error, 4000); }
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        alert(errorThrown);
                    }
                });
                return false;
            });
            $("#frmAdjuntarAnexo").submit(function () {
                var form = $(this);
                form.ajaxSubmit({
                    dataType: 'JSON',
                    type: 'POST',
                    url: form.attr('action'),
                    success: function (r) {
                        if (r.respuesta) {
                            Materialize.toast('Se Subió Correctamente!', 4000);                            
                            CargarAnexos();
                        }
                        else { Materialize.toast(r.error, 4000); }
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        alert(errorThrown);
                    }
                });
                return false;
            });
        });

        function CargarAnexos() {
            var url = "@Url.Action("MostrarAnexos", "Nacimiento")" + "?pNacimientoId=@Model.NacimientoId" + "&editar=true";
            $("#listarAnexos").load(url);
        };
        function EliminarAnexo(anexoid) {
            swal({
                title: "Estas seguro de eliminar este Anexo?",
                text: "Esta acción elimina el registro y el anexo digitalizada!",
                type: "warning",
                showCancelButton: true,
                cancelButtonText: "Cancelar",
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Eliminar",
                closeOnConfirm: false
            }, function () {
                $.ajax({
                    data: { id: anexoid },
                    url: '@Url.Action("EliminarAnexo", "Nacimiento")',
                    type: 'post',
                    success: function (r) {
                        CargarAnexos();
                        swal("Eliminado!", "El anexo ha sido eliminado.", "success");
                    },
                    error: function (jqXHR, textStatus, errorThrown) { alert(errorThrown); }
                });
            });
        }

    </script>
}