Web/Controllers/BandejaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace Web.Controllers
{
    public class BandejaController : Controller
    {
        // GET: Bandeja
        
        public ActionResult Index()
        {
           
            return View(BL.CajaMovBL.Listar(includeProperties:"persona"));
        }

        public ActionResult Mantener()
        {
            ViewBag.drpConcepto = new SelectList(BL.ConceptopagoBL.Listar(x => x.Estado), "ConceptoPagoId", "Denominacion");
            return View();

        }

       
    }
}

Web/Controllers/ComunController.cs
using BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Controllers
{
    public class ComunController : Controller
    {
        // GET: Comun
        public ActionResult ObtenerUsuarioSesion()
        {
            return Json(Comun.SessionHelper.GetUser(),JsonRequestBehavior.AllowGet);
        }
        

        public JsonResult ListarPersonas()
        {
            return Json(PersonaBL.Listar()
                          .Select(x => new { value = x.DNI + " - " + x.NombreCompleto, data = x.PersonaId })
                          .ToList()
            , JsonRequestBehavior.AllowGet);
        }
    }
}

Web/Views/Bandeja/Index.cshtml
@model IEnumerable<BE.cajamov>
@{ 
//var m = BL.CajaMovBL.Listar();
 }

<section id="content">

    <!--start container-->
    <div class="container">

        <div id="mail-app" class="section">
            <div class="row">
                <div class="col s12">
                    <nav class="red">
                        <div class="nav-wrapper">
                            <div class="left col s12 m5 l5">
                                <ul>
                                    <li>
                                        <a href="#!" class="email-menu"><i class="mdi-navigation-menu"></i></a>
                                    </li>
                                    <li>
                                        <a href="#!" class="email-type">Oficina</a>
                                    </li>
                                    <li class="right">
                                        <a href="#!"><i class="mdi-action-search"></i></a>
                                    </li>
                                </ul>
                            </div>
                            <div class="col s12 m7 l7 hide-on-med-and-down">
                                <ul class="right">
                                    <li>
                                        <a href="#!"><i class="mdi-content-archive"></i></a>
                                    </li>
                                    <li>
                                        <a href="#!"><i class="mdi-action-delete"></i></a>
                                    </li>
                                    <li>
                                        <a href="#!"><i class="mdi-content-mail"></i></a>
                                    </li>
                                    <li>
                                        <a href="#!"><i class="mdi-navigation-more-vert"></i></a>
                                    </li>
                                </ul>
                            </div>

                        </div>
                    </nav>
                </div>
                <div class="col s12">
                    <div id="email-sidebar" class="col s2 m1 s1 card-panel">
                        <ul>
                            <li>
                                <img src="images/avatar.jpg" alt="" class="circle responsive-img valign profile-image">
                            </li>
                            <li>
                                <a href="#!"><i class="mdi-content-archive active"></i></a>
                            </li>
                            <li>
                                <a href="#!"><i class="mdi-social-group"></i></a>
                            </li>
                            <li>
                                <a href="#!"><i class="mdi-maps-local-offer"></i></a>
                            </li>
                            <li>
                                <a href="#!"><i class="mdi-alert-error"></i></a>
                            </li>
                        </ul>
                    </div>
                    <div id="email-list" class="">
                        <ul class="collection">
                            
                            @{ int i = 0;}
                           @foreach (var item in Model)
                            {
                                i++;
                                <li class="collection-item avatar @if (i == 1) {<text>selected</text>}"
                                    ondblclick="MostrarEditar(@item.PersonaId);">
                                    <span class="circle light-blue">@item.persona.NombreCompleto.Substring(0, 1)</span>
                                    <span class="email-title">@item.persona.NombreCompleto</span>                                   
                                        <p class="truncate grey-text ultra-small">Monto @item.Monto</p>
                                        <p class="truncate grey-text ultra-small">Estado @item.Estado</p>
                                                                       
                                   @*<a class="secondary-content email-time"><span class="blue-text ultra-small"> @item.Monto</span></a>*@
                                </li>
                            }
                          
                        </ul>





                        
                    </div>
                    
                </div>
            </div>

            <!-- Compose Email Trigger -->
            <div class="fixed-action-btn" style="bottom: 50px; right: 19px;">
                <a class="btn btn-floating btn-large red" href='@Url.Action("Mantener","Bandeja",new { id=0 })'>
                    <i class="mdi-social-person-add"></i>
                </a>
            </div>



            <!-- Compose Email Structure -->
            
        </div>

    </div>
    <!--end container-->

</section>

Web/Views/Bandeja/Mantener.cshtml
<div class="row">
    <div class="col s12 m12 l12">
        <h5 class="breadcrumbs-title">Nuevo Pago </h5>
        <div class="card-panel row">
            <form id="formValidate" class="validar right-alert" method="post" action=''>
                <div class="row">
                    <div class="input-field col s11">
                        <input type="hidden" id="txtPersonaId" name="pPersonaId" value="0" />
                        <i class="mdi-action-search prefix"></i>
                        <input id="autocompletar" type="text" placeholder="DNI/Apellidos" required autofocus
                               data-url='@Url.Action("ListarPersonas","Comun")'
                               data-seleccion="txtPersonaId">
                        <label for="autocompletar" data-error="No existe la persona." data-success="Excelente!!! Persona encontrada.">Buscar Persona</label>
                    </div>
                    <div class="input-field col s1 valign-wrapper">
                        <a class="btn btn-floating tooltipped" data-tooltip="Crear Persona" data-position="left" href='@Url.Action("Mantener","Persona",new { id=0,href=Url.Action("Index","Home") })'>
                            <i class="mdi-social-person-add"></i>
                        </a>
                    </div>

                    <div class="input-field col s12 m4 l4">
                        @*<i class="mdi-file-file-download prefix"></i>*@
                        @Html.DropDownList("drpConcepto", (IEnumerable<SelectListItem>)ViewBag.drpConcepto)
                    </div>

                    <div  class="input-field col s12 m4 l4" >
                        <select id="cantidad">
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                        </select>                       
                    </div>
                    <div class="input-field col s12 m4 l4">
                        <button onclick="guardar(); return false;" class="btn waves-effect waves-light blue right" type="submit">
                            <i class="mdi-file-file-download left"></i>Agregar
                        </button>
                    </div>
                    <table>
                        <thead>
                            <tr>
                                <th>Concepto</th>
                                <th>Cantidad</th>
                                <th>Monto Total</th>
                            </tr>
                        </thead>
                        <tbody id="tabla">
                           
                        </tbody>
                    </table>
                    <div class="input-field col s12 m12 l12">
                        <button  class="btn waves-effect waves-light right" type="submit" >
                            <i class="mdi-content-send left"></i>Crear Pago
                        </button>
                    </div>
                </div>
                

            </form>

            
        </div>
    </div>
</div>


@section scripts{
    <script>   
        function guardar() {
            var _num = document.getElementById("drpConcepto");
            var _nom = _num.options[_num.selectedIndex].text;
            var _can = document.getElementById("cantidad").value;
            var fila = "<tr><td>" + _nom + "</td><td>" + _can + "</td><td>";
            var btn = document.createElement("TR");
            btn.innerHTML = fila;
            document.getElementById("tabla").appendChild(btn);
           //var _nom = document.getElementById("drpConcepto").value; (el numero)
        }
     </script>
}  